### ISSUE TITLE
Codeblocks flatpak does not follow system-wide GTK theme

### ISSUE THREAD

**Issue by juxi500** [flathub/org.codeblocks.codeblocks#2] opened 2018-09-16 22:19 UTC
Hello, I noticed that when Codeblocks is installed as flatpak application, it does not follow system-wide GTK theme (in my case Adwaita dark). It uses Adwaita light instead. When I run Codeblocks appimage, it follows system-wide GTK theme as expected.

EL7.5, flatpak ver. 0.8.8.

**Comment by TingPing** [comment] 2018-09-16 23:59
What is the output of `gsettings get org.gnome.desktop.interface gtk-theme`

**Comment by juxi500** [comment] 2018-09-17 08:10
`$ gsettings get org.gnome.desktop.interface gtk-theme`

`'Adwaita-dark'`

**Comment by TingPing** [comment] 2018-09-17 20:48
Well everything should just work, Adwaita-dark is certainly in the runtime. Not sure what would be at fault at a glance.

**Comment by juxi500** [comment] 2018-09-18 22:04
This is how it looks:

![screenshot from 2018-09-19 00-02-19](https://user-images.githubusercontent.com/38837830/45719037-61cfc280-bb9f-11e8-961a-451dcc95e1a7.png)

Notice dark themed Gnome system monitor, while Codeblocks is using light theme.

**Comment by tinywrkb** [comment] 2021-03-21 13:42
I can't reproduce. I'm not running a desktop environment but it's working as expected.

#### Test a: manual gsetting config

1. Set the theme with gsetting: `$ gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark`
2. Update flatpak so the theme will be auto-installed: `$ flatpak update`
3. Run the app

#### Test b: reading host env var

1. Steps 1,2 like a
2. Set `GTK_THEME=Adwaita-dark` globally or run `$ env GTK_THEME=Adwaita-dark flatpak run org.codeblocks.codeblocks`

#### Test c: override app var

1. Steps 1,2 like a
2. Override `GTK_THEME=Adwaita-dark` with Flatseal or `flatpak override` or run `$ flatpak run --env=GTK_THEME=Adwaita-dark org.codeblocks.codeblocks`

#### Test d: use the dark variant by reading host env var

Set `GTK_THEME=Adwaita:dark` globally or run `$ env GTK_THEME=Adwaita:dark flatpak run org.codeblocks.codeblocks`

#### Test e: use the dark variant by overriding app var

Override `GTK_THEME=Adwaita:dark` with Flatseal or `flatpak override` or run `$ flatpak run --env=GTK_THEME=Adwaita:dark org.codeblocks.codeblocks`

I also test `Arc-Dark` and confirmed it's working as it should.  
Closing, reopen if you still have an issue with the recent app version.

**Closed by tinywrkb** 2021-03-21 13:42 UTC
